# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kholidays' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-import-wizard' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/incidenceeditor' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/ktnef' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/libksieve' : '@same'
    'pim/mailcommon' : '@same'
    'pim/mailimporter' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'pim/kpkpass' : '@same'
    'pim/kitinerary' : '@same'
    'third-party/grantlee' : '@stable'
