# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kholidays' : '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/kcalendarcore': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/prison' : '@latest'
    'frameworks/kdeclarative' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-import-wizard' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/incidenceeditor' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/ktnef' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/libksieve' : '@same'
    'pim/mailcommon' : '@same'
    'pim/mailimporter' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'pim/kpkpass' : '@same'
    'pim/kitinerary' : '@same'
    'pim/kaddressbook' : '@same'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'libraries/ktexttemplate': '@stable'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'third-party/grantlee' : '@stable'
