# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kholidays': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/prison': 'Frameworks/6.24'
    'frameworks/kdeclarative': 'Frameworks/6.24'
    'frameworks/ktexttemplate': 'Frameworks/6.24'
    'pim/akonadi': '@same'
    'pim/akonadi-calendar': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/akonadi-import-wizard': '@same'
    'pim/calendarsupport': '@same'
    'pim/grantleetheme': '@same'
    'pim/incidenceeditor': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kimap': '@same'
    'pim/kmailtransport': '@same'
    'pim/kpimtextedit': '@same'
    'pim/ktnef': '@same'
    'pim/libgravatar': '@same'
    'pim/libkdepim': '@same'
    'pim/libkleo': '@same'
    'pim/libksieve': '@same'
    'pim/mailcommon': '@same'
    'pim/mailimporter': '@same'
    'pim/messagelib': '@same'
    'pim/pimcommon': '@same'
    'pim/kpkpass': '@same'
    'pim/kitinerary': '@same'
    'pim/kaddressbook': '@same'
    'libraries/ktextaddons': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'plasma/plasma-activities': '@latest-kf6'
    'frameworks/kcmutils': 'Frameworks/6.24'

Options:
 cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
 use-ccache: True
