# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kholidays' : '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/prison' : '@latest-kf6'
    'frameworks/kdeclarative' : '@latest-kf6'
    'frameworks/ktexttemplate': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-import-wizard' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/incidenceeditor' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/ktnef' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/libksieve' : '@same'
    'pim/mailcommon' : '@same'
    'pim/mailimporter' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'pim/kpkpass' : '@same'
    'pim/kitinerary' : '@same'
    'pim/kaddressbook' : '@same'
    'libraries/ktextaddons': '@latest-kf6'
