version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "kdepim-addons"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/kdepim-addons"

[[annotations]]
path = ["plugins/plasma/pimeventsplugin/autotests/data/**", "plugins/messageviewerplugins/externalscriptplugin/autotests/externaldatas/**", "plugins/messageviewerheaderplugins/autotests/data/**", "plugins/messageviewer/bodypartformatter/autotests/gnupg_home/**", "kmail/grammarplugins/grammalecte/autotests/data/**", "kmail/editorsendcheckplugins/automaticaddcontacts/autotests/unittestenv/**", "kaddressbook/plugins/sendvcards/autotests/unittestenv/**", "kaddressbook/plugins/sendmail/autotests/unittestenv/**", "kaddressbook/plugins/mergelib/autotests/unittestenv/**", "kaddressbook/plugins/checkgravatar/gravatar/autotests/unittestenv/**", "kaddressbook/importexportplugins/windows-contacts/autotests/data/**", "plugins/messageviewer/bodypartformatter/autotests/data/**", "kmail/editorconvertertextplugins/markdown/tests/test.txt", "kmail/plugins/common/kmail.antispamrc", "kmail/plugins/common/kmail.antispamrc-HOWTO", "kmail/plugins/common/kmail.antivirusrc", "korganizer/plugins/hebrew/README", "plugins/messageviewer/bodypartformatter/autotests/data/**", "plugins/messageviewerplugins/externalscriptplugin/README"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
