/*
   SPDX-FileCopyrightText: 2025 Laurent Montel <montel@kde.org>

   SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "aitooltextplugineditorinterface.h"
#include <KActionCollection>
#include <PimAutoGenerateText/AutogenerateConfigureAskManager>
#include <PimAutoGenerateText/AutogenerateConfigureAskMenu>
#include <QAction>
#include <QMenu>
#include <TextAutoGenerateText/TextAutoGenerateDialog>
#include <TextCustomEditor/RichTextEditor>

AIToolTextPluginEditorInterface::AIToolTextPluginEditorInterface(QObject *parent)
    : MessageComposer::PluginEditorInterface(parent)
{
    setNeedSelectedText(true);
}

AIToolTextPluginEditorInterface::~AIToolTextPluginEditorInterface() = default;

void AIToolTextPluginEditorInterface::createAction(KActionCollection *ac)
{
    /*
    auto menu = new AutogenerateConfigureAskMenu(mAskManager, this);
    connect(this, &AIToolTextPluginEditorInterface::refreshMenu, menu, &AutogenerateConfigureAskMenu::slotRefreshMenu);
    ac->addAction(QStringLiteral("editor_ia_tool"), menu);
    connect(menu, &AutogenerateConfigureAskMenu::askRequested, this, &AIToolTextPluginEditorInterface::slotAskRequested);
    MessageComposer::PluginActionType type(menu, MessageComposer::PluginActionType::Tools);
    setActionType(type);
    */
}

void AIToolTextPluginEditorInterface::exec()
{
    auto dlg = new TextAutoGenerateText::TextAutoGenerateDialog(parentWidget());
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->show();
}

#include "moc_aitooltextplugineditorinterface.cpp"
