/*
   SPDX-FileCopyrightText: 2025 Laurent Montel <montel@kde.org>

   SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "askautogeneratetextplugineditorinterface.h"
#include <KActionCollection>
#include <PimAutoGenerateText/AutogenerateConfigureAskManager>
#include <PimAutoGenerateText/AutogenerateConfigureAskMenu>
#include <QAction>
#include <QMenu>
#include <TextAutoGenerateText/TextAutoGenerateDialog>
#include <TextCustomEditor/RichTextEditor>

AskAutogenerateTextPluginEditorInterface::AskAutogenerateTextPluginEditorInterface(QObject *parent)
    : MessageComposer::PluginEditorInterface(parent)
    , mAskManager(new AutogenerateConfigureAskManager(this))
{
    setNeedSelectedText(true);
}

AskAutogenerateTextPluginEditorInterface::~AskAutogenerateTextPluginEditorInterface() = default;

void AskAutogenerateTextPluginEditorInterface::createAction(KActionCollection *ac)
{
    auto menu = new AutogenerateConfigureAskMenu(mAskManager, this);
    connect(this, &AskAutogenerateTextPluginEditorInterface::refreshMenu, menu, &AutogenerateConfigureAskMenu::slotRefreshMenu);
    ac->addAction(QStringLiteral("editor_ask_ia"), menu);
    connect(menu, &AutogenerateConfigureAskMenu::askRequested, this, &AskAutogenerateTextPluginEditorInterface::slotAskRequested);
    MessageComposer::PluginActionType type(menu, MessageComposer::PluginActionType::Edit);
    setActionType(type);
}

void AskAutogenerateTextPluginEditorInterface::slotAskRequested(const QString &msg)
{
    auto dlg = new TextAutoGenerateText::TextAutoGenerateDialog(parentWidget());
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->show();
    // TODO dlg->ask(QStringLiteral("%1 %2").arg(msg, mSelectedText));
    // TODO
}

void AskAutogenerateTextPluginEditorInterface::exec()
{
    // TODO
}

void AskAutogenerateTextPluginEditorInterface::slotRefreshMenu()
{
    Q_EMIT refreshMenu();
}

#include "moc_askautogeneratetextplugineditorinterface.cpp"
